# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='한글이름', max_length=30, verbose_name='성명')),
                ('user_company', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('HUMAN', 'HUMAN'), ('DEVICE', 'DEVICE')], default='HUMAN', max_length=5)),
                ('user_group', models.CharField(choices=[('SI', 'SI'), ('SM', 'SM')], default='SI', max_length=2)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('contract_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('비비엠씨(주)', '비비엠씨(주)'), ('(주)지엠솔루션', '(주)지엠솔루션'), ('(주)더피프티원', '(주)더피프티원'), ('(주)비즈테크파트너스', '(주)비즈테크파트너스')], max_length=20)),
                ('member_name', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=50)),
                ('man_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('contract_level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False, unique=True)),
                ('ip_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('team', models.CharField(default='마케팅플랫폼팀', max_length=20)),
                ('project_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('project_manager', models.CharField(max_length=20)),
                ('sm_si', models.CharField(choices=[('si', 'si'), ('sm', 'sm')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Officeplus',
            fields=[
                ('contractmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='lgcom.ContractMember')),
                ('external_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgcom.Project', to_field='project_name')),
            ],
            bases=('lgcom.contractmember',),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='ipuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractmember',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgcom.Contract', to_field='contract_name'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgcom.Project', to_field='project_name'),
        ),
    ]
