# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgcom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='ip_status',
            field=models.BooleanField(default=False),
        ),
    ]
