# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgcom', '0002_ipaddress_ip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_status',
            field=models.BooleanField(),
        ),
    ]
