# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgcom', '0004_ipaddress_ip_use_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_status',
            field=models.BooleanField(default=False),
        ),
    ]
